### ISSUE TITLE
how do i run this on Linux?

### ISSUE THREAD

**Issue by svlungade** [skmp/node-msoffice-pdf#2]
Could you please give detailed instructions how to run this on linux env?

**Comment by 360disrupt** [comment]
Does `Depends on office 2013 + windows.` mean, that it will only work on a windows machine with office installed?

**Comment by skmp** [comment]
Yup. This is just a bridge for automating built-in office functionality.

**Comment by skmp** [comment]
This cannot run on linux. It depends on office and windows.
