### ISSUE TITLE
Suggestions for how to run this as a service?

### ISSUE THREAD

**Issue by jbrozena22** [skmp/node-msoffice-pdf#7]
Since this depends on MS-office, are there any best practices for how to set this up as a standalone web service? I have no experience with Azure, but I assume there is an optimal setup with a windows server that could make this work?

Looking for suggestions and tips from those using this.

Thanks!

**Comment by skmp** [comment]
It's been a long time since I last used this module. Did you get it working? Would be great to have a guide on the readme :)

**Comment by skmp** [comment]
(closing this as it is unlikely to be answered)
